"""add price range support and services offered post type

Revision ID: 6ead5c7042df
Revises: f8101a26faef
Create Date: 2026-05-31 17:34:42.690959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ead5c7042df'
down_revision = 'f8101a26faef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('min_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('post_type', sa.String(length=20), nullable=True, server_default='sale'))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('allow_comments',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('allow_comments',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('post_type')
        batch_op.drop_column('max_price')
        batch_op.drop_column('min_price')
        batch_op.drop_column('price_type')

    # ### end Alembic commands ###