"""add photo_url field

Revision ID: bcfc95aa618a
Revises: cb63c0706e88
Create Date: 2026-05-20 12:55:20.950129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bcfc95aa618a'
down_revision = 'cb63c0706e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('photos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sqlite.JSON(), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
