"""Add allow_comments to Listing

Revision ID: f8101a26faef
Revises: bcfc95aa618a
Create Date: 2026-05-20 18:54:18.143874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8101a26faef'
down_revision = 'bcfc95aa618a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=False))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('allow_comments')

    # ### end Alembic commands ###
